# Generated by Django 3.2.6 on 2021-08-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('mango_requirement', models.IntegerField()),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MangoFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=50)),
                ('max_mangos', models.IntegerField()),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
            ],
        ),
    ]
