# Generated by Django 3.2.6 on 2021-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
