# Generated by Django 3.2.6 on 2021-08-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0002_customer_blacklisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
    ]
